export const CMS_PERMISSION_CATALOG = [
  ["dashboard", "Dashboard"], ["home", "Página Inicial"], ["services", "Página Serviços"], ["about-page", "Página Sobre"], ["business-page", "Página Empresas"], ["contact-page", "Página Contato"], ["careers-page", "Página Carreiras"], ["collections", "Página Coletas"], ["quote-page", "Página Cotação"], ["improvements", "Página Melhoria"], ["header-navigation", "Navegação"], ["footer-links", "Rodapé"], ["units", "Unidades"], ["analytics", "Analytics"], ["images", "Imagens"], ["popup", "Popup de saída"], ["tracking", "Rastreamento"], ["seo", "SEO"], ["cookie-monitoring", "Consentimentos"], ["leads", "Leads"], ["cookies", "LGPD e cookies"], ["users", "Usuários e acessos"], ["landing-pages", "Landing Pages"],
] as const;
export type CmsPermission = (typeof CMS_PERMISSION_CATALOG)[number][0];
export function permissionForAdminPath(pathname: string): CmsPermission | null {
  const logicalPathname = normalizeCmsPathname(pathname);
  const match: Array<[string, CmsPermission]> = [["/developer/landing-pages", "landing-pages"], ["/developer/analytics", "analytics"], ["/developer/coletas", "collections"], ["/developer/contato-info", "contact-page"], ["/developer/cotacao", "quote-page"], ["/developer/fale-conosco", "contact-page"], ["/developer/footer-links", "footer-links"], ["/developer/home", "home"], ["/developer/imagens", "images"], ["/developer/leads", "leads"], ["/developer/lgpd-cookies", "cookies"], ["/developer/melhorias", "improvements"], ["/developer/monitoramento-cookies", "cookie-monitoring"], ["/developer/navegacao", "header-navigation"], ["/developer/para-empresas", "business-page"], ["/developer/popup-exit", "popup"], ["/developer/rastreamento", "tracking"], ["/developer/seo", "seo"], ["/developer/servicos-feedbacks", "home"], ["/developer/servicos", "services"], ["/developer/sobre", "about-page"], ["/developer/trabalhe-conosco", "careers-page"], ["/developer/unidades", "units"], ["/developer/usuarios", "users"], ["/developer/vagas", "careers-page"]];
  if (logicalPathname === "/developer") return "dashboard";
  return match.find(([prefix]) => logicalPathname.startsWith(prefix))?.[1] ?? null;
}
import { normalizeCmsPathname } from "@/lib/routes";
