spring.application.name=rodogarcia-site-backend
spring.main.banner-mode=off
spring.mvc.formcontent.filter.enabled=false
spring.mvc.problemdetails.enabled=false
spring.servlet.multipart.enabled=false
spring.web.resources.add-mappings=false

server.compression.enabled=false
server.error.whitelabel.enabled=false
server.error.include-message=never
server.error.include-stacktrace=never
server.forward-headers-strategy=none
server.servlet.session.timeout=0

logging.level.root=INFO
logging.level.org.springframework.web=WARN
logging.level.org.springframework.web.servlet.PageNotFound=OFF
