"use client";

import { Plus } from "@phosphor-icons/react";
import {
  DeveloperCard,
  DeveloperField,
  DeveloperHelp,
  DeveloperSectionHeading,
  developerInputClassName,
  developerSecondaryButtonClassName,
} from "../ui";

export type CampaignV1Sections = {
  lowerSection: { visible: boolean; title: string; description: string; ctaLabel: string; ctaUrl: string };
  benefits: { visible: boolean; eyebrow: string; title: string; description: string; items: Array<{ title: string; description: string }> };
  story: { visible: boolean; eyebrow: string; title: string; description: string; image: string; ctaLabel: string; ctaUrl: string };
  metrics: { visible: boolean; eyebrow: string; title: string; items: Array<{ value: string; label: string }> };
  testimonial: { visible: boolean; eyebrow: string; title: string; quote: string; author: string; role: string };
  faq: { visible: boolean; eyebrow: string; title: string; items: Array<{ question: string; answer: string }> };
  finalCta: { visible: boolean; eyebrow: string; title: string; description: string; ctaLabel: string; ctaUrl: string };
  footer: { brand: string; description: string; phone: string; email: string; legalText: string };
};

type CampaignMedia = { id: string; url: string; kind: string; alt?: string };

function VisibilityToggle({ checked, onChange }: { checked: boolean; onChange: (visible: boolean) => void }) {
  return <label className="inline-flex min-h-9 items-center gap-2 rounded-lg border border-[var(--border)] bg-white px-3 py-1.5 text-xs font-semibold text-[var(--foreground)]"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="size-4 accent-[var(--primary)]" />Exibir seção<DeveloperHelp label="Visibilidade da seção" templateKey="landing-pages.field.section-visibility" /></label>;
}

function TextPair({ title, description, onChange }: { title: string; description: string; onChange: (value: { title: string; description: string }) => void }) {
  return <div className="grid gap-3 rounded-xl border border-[var(--border)] bg-white p-3 md:grid-cols-2"><DeveloperField label="Título"><input value={title} onChange={(event) => onChange({ title: event.target.value, description })} className={developerInputClassName} maxLength={80} /></DeveloperField><DeveloperField label="Descrição"><textarea value={description} onChange={(event) => onChange({ title, description: event.target.value })} className={`${developerInputClassName} min-h-20 resize-y`} maxLength={220} /></DeveloperField></div>;
}

/** Editor do conteúdo abaixo do Hero para o template fechado campaign-v1. */
export function CampaignV1SectionsEditor<T extends CampaignV1Sections>({ landing, media, onChange }: { landing: T; media: CampaignMedia[]; onChange: (update: (current: T) => T) => void }) {
  const imageMedia = media.filter((item) => item.kind === "image");
  const update = <K extends keyof CampaignV1Sections>(key: K, value: CampaignV1Sections[K]) => onChange((current) => ({ ...current, [key]: value }));

  return <div className="space-y-5">
    <DeveloperCard>
      <DeveloperSectionHeading eyebrow="Template padrão" title="Apresentação" description="A primeira seção após o Hero aprofunda a proposta principal da campanha." action={<VisibilityToggle checked={landing.lowerSection.visible} onChange={(visible) => update("lowerSection", { ...landing.lowerSection, visible })} />} />
      <div className="grid gap-4 md:grid-cols-2"><DeveloperField label="Título"><input value={landing.lowerSection.title} onChange={(event) => update("lowerSection", { ...landing.lowerSection, title: event.target.value })} className={developerInputClassName} maxLength={180} /></DeveloperField><DeveloperField label="Descrição"><textarea value={landing.lowerSection.description} onChange={(event) => update("lowerSection", { ...landing.lowerSection, description: event.target.value })} className={`${developerInputClassName} min-h-28 resize-y`} maxLength={900} /></DeveloperField><DeveloperField label="Botão"><input value={landing.lowerSection.ctaLabel} onChange={(event) => update("lowerSection", { ...landing.lowerSection, ctaLabel: event.target.value })} className={developerInputClassName} maxLength={70} /></DeveloperField><DeveloperField label="Destino do botão"><input value={landing.lowerSection.ctaUrl} onChange={(event) => update("lowerSection", { ...landing.lowerSection, ctaUrl: event.target.value })} className={developerInputClassName} maxLength={400} /></DeveloperField></div>
    </DeveloperCard>

    <DeveloperCard>
      <DeveloperSectionHeading eyebrow="Template padrão" title="Benefícios" description="Mostre de um a seis motivos objetivos para a pessoa avançar na campanha." action={<VisibilityToggle checked={landing.benefits.visible} onChange={(visible) => update("benefits", { ...landing.benefits, visible })} />} />
      <div className="grid gap-4 md:grid-cols-2"><DeveloperField label="Selo"><input value={landing.benefits.eyebrow} onChange={(event) => update("benefits", { ...landing.benefits, eyebrow: event.target.value })} className={developerInputClassName} maxLength={80} /></DeveloperField><DeveloperField label="Título"><input value={landing.benefits.title} onChange={(event) => update("benefits", { ...landing.benefits, title: event.target.value })} className={developerInputClassName} maxLength={180} /></DeveloperField></div><DeveloperField label="Descrição" className="mt-4"><textarea value={landing.benefits.description} onChange={(event) => update("benefits", { ...landing.benefits, description: event.target.value })} className={`${developerInputClassName} min-h-24 resize-y`} maxLength={700} /></DeveloperField><div className="mt-4 grid gap-3">{landing.benefits.items.map((item, index) => <TextPair key={index} title={item.title} description={item.description} onChange={(value) => update("benefits", { ...landing.benefits, items: landing.benefits.items.map((current, currentIndex) => currentIndex === index ? value : current) })} />)}</div>{landing.benefits.items.length < 6 ? <button type="button" onClick={() => update("benefits", { ...landing.benefits, items: [...landing.benefits.items, { title: "Novo benefício", description: "Explique este benefício." }] })} className={`${developerSecondaryButtonClassName} mt-4`}><Plus size={16} weight="bold" />Adicionar benefício</button> : null}
    </DeveloperCard>

    <DeveloperCard>
      <DeveloperSectionHeading eyebrow="Template padrão" title="Imagem e texto" description="Explique como a solução funciona ao lado de uma imagem da biblioteca da própria campanha." action={<VisibilityToggle checked={landing.story.visible} onChange={(visible) => update("story", { ...landing.story, visible })} />} />
      <div className="grid gap-4 md:grid-cols-2"><DeveloperField label="Selo"><input value={landing.story.eyebrow} onChange={(event) => update("story", { ...landing.story, eyebrow: event.target.value })} className={developerInputClassName} maxLength={80} /></DeveloperField><DeveloperField label="Título"><input value={landing.story.title} onChange={(event) => update("story", { ...landing.story, title: event.target.value })} className={developerInputClassName} maxLength={180} /></DeveloperField><DeveloperField label="Imagem" helpKey="landing-pages.field.story-image"><select value={landing.story.image} onChange={(event) => update("story", { ...landing.story, image: event.target.value })} className={developerInputClassName}><option value="">Sem imagem</option>{imageMedia.map((item) => <option key={item.id} value={item.url}>{item.alt || item.id}</option>)}</select></DeveloperField><DeveloperField label="Botão"><input value={landing.story.ctaLabel} onChange={(event) => update("story", { ...landing.story, ctaLabel: event.target.value })} className={developerInputClassName} maxLength={70} /></DeveloperField><DeveloperField label="Descrição" className="md:col-span-2"><textarea value={landing.story.description} onChange={(event) => update("story", { ...landing.story, description: event.target.value })} className={`${developerInputClassName} min-h-28 resize-y`} maxLength={900} /></DeveloperField><DeveloperField label="Destino do botão" className="md:col-span-2"><input value={landing.story.ctaUrl} onChange={(event) => update("story", { ...landing.story, ctaUrl: event.target.value })} className={developerInputClassName} maxLength={400} /></DeveloperField></div>
    </DeveloperCard>

    <DeveloperCard>
      <DeveloperSectionHeading eyebrow="Template padrão" title="Números" description="Use indicadores curtos para reforçar a proposta da campanha." action={<VisibilityToggle checked={landing.metrics.visible} onChange={(visible) => update("metrics", { ...landing.metrics, visible })} />} />
      <div className="grid gap-4 md:grid-cols-2"><DeveloperField label="Selo"><input value={landing.metrics.eyebrow} onChange={(event) => update("metrics", { ...landing.metrics, eyebrow: event.target.value })} className={developerInputClassName} maxLength={80} /></DeveloperField><DeveloperField label="Título"><input value={landing.metrics.title} onChange={(event) => update("metrics", { ...landing.metrics, title: event.target.value })} className={developerInputClassName} maxLength={180} /></DeveloperField></div><div className="mt-4 grid gap-3 md:grid-cols-3">{landing.metrics.items.map((item, index) => <div key={index} className="rounded-xl border border-[var(--border)] bg-white p-3"><DeveloperField label="Número"><input value={item.value} onChange={(event) => update("metrics", { ...landing.metrics, items: landing.metrics.items.map((current, currentIndex) => currentIndex === index ? { ...current, value: event.target.value } : current) })} className={developerInputClassName} maxLength={40} /></DeveloperField><DeveloperField label="Legenda" className="mt-3"><input value={item.label} onChange={(event) => update("metrics", { ...landing.metrics, items: landing.metrics.items.map((current, currentIndex) => currentIndex === index ? { ...current, label: event.target.value } : current) })} className={developerInputClassName} maxLength={120} /></DeveloperField></div>)}</div>{landing.metrics.items.length < 4 ? <button type="button" onClick={() => update("metrics", { ...landing.metrics, items: [...landing.metrics.items, { value: "04", label: "Novo indicador" }] })} className={`${developerSecondaryButtonClassName} mt-4`}><Plus size={16} weight="bold" />Adicionar número</button> : null}
    </DeveloperCard>

    <DeveloperCard>
      <DeveloperSectionHeading eyebrow="Template padrão" title="Depoimento" description="Apresente uma fala real que reforce a confiança na campanha." action={<VisibilityToggle checked={landing.testimonial.visible} onChange={(visible) => update("testimonial", { ...landing.testimonial, visible })} />} />
      <div className="grid gap-4 md:grid-cols-2"><DeveloperField label="Selo"><input value={landing.testimonial.eyebrow} onChange={(event) => update("testimonial", { ...landing.testimonial, eyebrow: event.target.value })} className={developerInputClassName} maxLength={80} /></DeveloperField><DeveloperField label="Título"><input value={landing.testimonial.title} onChange={(event) => update("testimonial", { ...landing.testimonial, title: event.target.value })} className={developerInputClassName} maxLength={180} /></DeveloperField><DeveloperField label="Depoimento" className="md:col-span-2"><textarea value={landing.testimonial.quote} onChange={(event) => update("testimonial", { ...landing.testimonial, quote: event.target.value })} className={`${developerInputClassName} min-h-28 resize-y`} maxLength={900} /></DeveloperField><DeveloperField label="Nome"><input value={landing.testimonial.author} onChange={(event) => update("testimonial", { ...landing.testimonial, author: event.target.value })} className={developerInputClassName} maxLength={100} /></DeveloperField><DeveloperField label="Cargo ou empresa"><input value={landing.testimonial.role} onChange={(event) => update("testimonial", { ...landing.testimonial, role: event.target.value })} className={developerInputClassName} maxLength={120} /></DeveloperField></div>
    </DeveloperCard>

    <DeveloperCard>
      <DeveloperSectionHeading eyebrow="Template padrão" title="Perguntas frequentes" description="Antecipe as dúvidas que podem impedir o contato." action={<VisibilityToggle checked={landing.faq.visible} onChange={(visible) => update("faq", { ...landing.faq, visible })} />} />
      <div className="grid gap-3">{landing.faq.items.map((item, index) => <div key={index} className="rounded-xl border border-[var(--border)] bg-white p-3"><DeveloperField label="Pergunta"><input value={item.question} onChange={(event) => update("faq", { ...landing.faq, items: landing.faq.items.map((current, currentIndex) => currentIndex === index ? { ...current, question: event.target.value } : current) })} className={developerInputClassName} maxLength={180} /></DeveloperField><DeveloperField label="Resposta" className="mt-3"><textarea value={item.answer} onChange={(event) => update("faq", { ...landing.faq, items: landing.faq.items.map((current, currentIndex) => currentIndex === index ? { ...current, answer: event.target.value } : current) })} className={`${developerInputClassName} min-h-24 resize-y`} maxLength={900} /></DeveloperField></div>)}</div>{landing.faq.items.length < 8 ? <button type="button" onClick={() => update("faq", { ...landing.faq, items: [...landing.faq.items, { question: "Nova pergunta", answer: "Escreva uma resposta clara." }] })} className={`${developerSecondaryButtonClassName} mt-4`}><Plus size={16} weight="bold" />Adicionar pergunta</button> : null}
    </DeveloperCard>

    <DeveloperCard>
      <DeveloperSectionHeading eyebrow="Template padrão" title="CTA final" description="Feche a campanha com uma chamada clara para a ação principal." action={<VisibilityToggle checked={landing.finalCta.visible} onChange={(visible) => update("finalCta", { ...landing.finalCta, visible })} />} />
      <div className="grid gap-4 md:grid-cols-2"><DeveloperField label="Selo"><input value={landing.finalCta.eyebrow} onChange={(event) => update("finalCta", { ...landing.finalCta, eyebrow: event.target.value })} className={developerInputClassName} maxLength={80} /></DeveloperField><DeveloperField label="Título"><input value={landing.finalCta.title} onChange={(event) => update("finalCta", { ...landing.finalCta, title: event.target.value })} className={developerInputClassName} maxLength={180} /></DeveloperField><DeveloperField label="Descrição" className="md:col-span-2"><textarea value={landing.finalCta.description} onChange={(event) => update("finalCta", { ...landing.finalCta, description: event.target.value })} className={`${developerInputClassName} min-h-24 resize-y`} maxLength={700} /></DeveloperField><DeveloperField label="Botão"><input value={landing.finalCta.ctaLabel} onChange={(event) => update("finalCta", { ...landing.finalCta, ctaLabel: event.target.value })} className={developerInputClassName} maxLength={70} /></DeveloperField><DeveloperField label="Destino do botão"><input value={landing.finalCta.ctaUrl} onChange={(event) => update("finalCta", { ...landing.finalCta, ctaUrl: event.target.value })} className={developerInputClassName} maxLength={400} /></DeveloperField></div>
    </DeveloperCard>

    <DeveloperCard>
      <DeveloperSectionHeading eyebrow="Template padrão" title="Rodapé" description="Mostre a identificação e os canais finais da campanha." />
      <div className="grid gap-4 md:grid-cols-2"><DeveloperField label="Marca"><input value={landing.footer.brand} onChange={(event) => update("footer", { ...landing.footer, brand: event.target.value })} className={developerInputClassName} maxLength={120} /></DeveloperField><DeveloperField label="Telefone"><input value={landing.footer.phone} onChange={(event) => update("footer", { ...landing.footer, phone: event.target.value })} className={developerInputClassName} maxLength={40} /></DeveloperField><DeveloperField label="Descrição"><textarea value={landing.footer.description} onChange={(event) => update("footer", { ...landing.footer, description: event.target.value })} className={`${developerInputClassName} min-h-24 resize-y`} maxLength={400} /></DeveloperField><DeveloperField label="E-mail"><input value={landing.footer.email} onChange={(event) => update("footer", { ...landing.footer, email: event.target.value })} className={developerInputClassName} maxLength={160} /></DeveloperField><DeveloperField label="Texto legal" className="md:col-span-2"><input value={landing.footer.legalText} onChange={(event) => update("footer", { ...landing.footer, legalText: event.target.value })} className={developerInputClassName} maxLength={240} /></DeveloperField></div>
    </DeveloperCard>
  </div>;
}
