spring.application.name=rodogarcia-cms-backend
spring.main.banner-mode=off
spring.mvc.formcontent.filter.enabled=false
spring.mvc.problemdetails.enabled=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
spring.servlet.multipart.enabled=true
spring.servlet.multipart.resolve-lazily=true
spring.servlet.multipart.max-file-size=70MB
spring.servlet.multipart.max-request-size=70MB

server.compression.enabled=false
server.error.whitelabel.enabled=false
server.error.include-message=never
server.error.include-stacktrace=never
server.forward-headers-strategy=none
server.servlet.session.timeout=0

logging.level.root=INFO
logging.level.org.springframework.web=WARN
logging.level.org.springframework.web.servlet.PageNotFound=OFF
