spring.application.name=rodogarcia-landing-builder-backend
spring.main.banner-mode=off
spring.mvc.formcontent.filter.enabled=false
spring.mvc.problemdetails.enabled=false
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=70MB
spring.servlet.multipart.max-request-size=73465856B
spring.servlet.multipart.file-size-threshold=1MB
spring.web.resources.add-mappings=false

server.address=${LANDING_BUILDER_HOST:${HOST:127.0.0.1}}
server.port=${LANDING_BUILDER_PORT:${PORT:36110}}
server.compression.enabled=false
server.error.whitelabel.enabled=false
server.error.include-message=never
server.error.include-stacktrace=never
server.forward-headers-strategy=none
server.servlet.session.timeout=0
server.tomcat.max-http-form-post-size=73465856B
server.tomcat.max-swallow-size=73465856B

logging.level.root=INFO
logging.level.org.springframework.web=WARN
logging.level.org.springframework.web.servlet.PageNotFound=OFF
