import fs from "node:fs";
import { afterEach, describe, expect, it, vi } from "vitest";
import { createIsolatedBackendEnv } from "./testEnv.js";

const temporaryRoots: string[] = [];

afterEach(() => {
  vi.unstubAllGlobals();
  for (const root of temporaryRoots.splice(0)) {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

async function loadService() {
  const isolated = createIsolatedBackendEnv();
  temporaryRoots.push(isolated.root);
  process.env.LANDING_BUILDER_API_URL = "http://127.0.0.1:6110";
  process.env.LANDING_BUILDER_SERVICE_TOKEN = "landing-builder-test-token-with-at-least-32-chars";
  return import("../src/services/landingBuilderService.js");
}

describe("Landing Builder service proxy", () => {
  it("sends JSON mutations with only the private service credential", async () => {
    const fetchMock = vi.fn(async () => new Response(JSON.stringify({ landing: { id: "landing_1" } }), {
      status: 201,
      headers: { "content-type": "application/json" },
    }));
    vi.stubGlobal("fetch", fetchMock);
    const { createLandingPage, getLandingPreview } = await loadService();

    await createLandingPage({ name: "Campanha", slug: "campanha", seo: {}, theme: {}, analytics: {}, hero: {}, lowerSection: {} });
    await getLandingPreview("landing_1");

    const [createUrl, createInit] = fetchMock.mock.calls[0] ?? [];
    expect(createUrl).toBe("http://127.0.0.1:6110/api/internal/landings");
    expect(createInit).toMatchObject({ method: "POST" });
    const createHeaders = new Headers((createInit as RequestInit).headers);
    expect(createHeaders.get("x-landing-builder-service-token")).toMatch(/^landing-builder-test-token/);
    expect(createHeaders.get("content-type")).toBe("application/json");

    const [previewUrl, previewInit] = fetchMock.mock.calls[1] ?? [];
    expect(previewUrl).toBe("http://127.0.0.1:6110/api/internal/landings/landing_1/preview");
    expect(previewInit).toMatchObject({ method: "POST" });
    expect(new Headers((previewInit as RequestInit).headers).get("content-type")).toBeNull();
  });

  it("keeps the multipart boundary generated by fetch when forwarding media", async () => {
    const fetchMock = vi.fn(async () => new Response(JSON.stringify({ media: { id: "media_1" } }), {
      status: 201,
      headers: { "content-type": "application/json" },
    }));
    vi.stubGlobal("fetch", fetchMock);
    const { uploadLandingMedia } = await loadService();
    const file = {
      buffer: Buffer.from([0x89, 0x50, 0x4e, 0x47]),
      mimetype: "image/png",
      originalname: "campanha.png",
    } as Express.Multer.File;

    await uploadLandingMedia(file, "Imagem da campanha");

    const [url, init] = fetchMock.mock.calls[0] ?? [];
    expect(url).toBe("http://127.0.0.1:6110/api/internal/media");
    expect(init).toMatchObject({ method: "POST" });
    expect((init as RequestInit).body).toBeInstanceOf(FormData);
    const headers = new Headers((init as RequestInit).headers);
    expect(headers.get("x-landing-builder-service-token")).toMatch(/^landing-builder-test-token/);
    expect(headers.get("content-type")).toBeNull();
  });
});
